name: Use OpenAI Secret

on: [push]

jobs:
  access-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Access OpenAI Key
        run: echo "The secret is ${{ secrets.OPENAI_KEY }}"
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
