# This workflow # Car Game Program

# Initialize player's car position and speed
car_position = 0
car_speed = 0

# Game loop
while True:
    # Print current car position and speed
    print(f"Car Position: {car_position} | Car Speed: {car_speed}")

    # Ask user for action
    action = input("Enter 'accelerate', 'brake', or 'exit': ")

    # Handle user action
    if action == "accelerate":
        car_speed += 10
        car_position += car_speed
    elif action == "brake":
        car_speed -= 10
        if car_speed < 0:
            car_speed = 0
    elif action == "exit":
        break
    else:
        print("Invalid action. Please try again.")

# Game over
print("Game over. Final car position:", car_position)
 upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{sanjay}}
